### ISSUE TITLE
Discord reminder 

### ISSUE THREAD

**Issue by ironsniper1** [Redherring32/OpenTendo-TopLoader#1]
Finny (grievre/arreffem) — Today at 9:58 PM
I found it thanks ❤️
@Redherring32 (The Fish) these are mislabeled, they're not shift registers. They're connected to shift registers (in the controllers), but the '368 is an inverting buffer/line driver chip

Redherring32 (The Fish) — Today at 10:01 PM
Hex buffers no? I meant to change that label actually but I'm a very forgetful person. 

Finny (grievre/arreffem) — Today at 11:07 PM
Yeah. I would also label them 74HC368/40H368 since the latter is a weird Toshiba specific part number that wasn't even consistently used on the original hardware.

**Comment by Redherring32** [comment]
Fixed in https://github.com/Redherring32/OpenTendo-TopLoader/commit/5f63f3e56a1f03a32ac05688f1c16b8a02da2a24
